name: Detalhes do Workflow
on:
  workflow_dispatch:
jobs:
  workflow-info:
    name: Job para exibir detalhes do Workflow
    runs-on: ubuntu-latest
    env: 
       HELLO_WORLD: "Hello, World!"
    steps:
      - name: Exibir "Hello, World!"
        run: echo  "${{env.HELLO_WORLD}}"

      - name: Show github context
        #| executa comandos com mais de uma linha
        run: |
          echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
          echo "${{toJson(github)}}"