# Nome do job
name: Primeiro Workflow, Hello World

on:
  workflow_dispatch:
jobs:
  job_hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: Exibir mensagem de Hello World
        run: echo "Hello, World!"